#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavTakvimi.VeriTabani
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="doganvar_veritabani")]
	public partial class VeriTabaniDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAsistanlar(Asistanlar instance);
    partial void UpdateAsistanlar(Asistanlar instance);
    partial void DeleteAsistanlar(Asistanlar instance);
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertBolumler(Bolumler instance);
    partial void UpdateBolumler(Bolumler instance);
    partial void DeleteBolumler(Bolumler instance);
    partial void InsertDersler(Dersler instance);
    partial void UpdateDersler(Dersler instance);
    partial void DeleteDersler(Dersler instance);
    partial void InsertDerslikler(Derslikler instance);
    partial void UpdateDerslikler(Derslikler instance);
    partial void DeleteDerslikler(Derslikler instance);
    partial void InsertIzinler(Izinler instance);
    partial void UpdateIzinler(Izinler instance);
    partial void DeleteIzinler(Izinler instance);
    partial void InsertSekreterler(Sekreterler instance);
    partial void UpdateSekreterler(Sekreterler instance);
    partial void DeleteSekreterler(Sekreterler instance);
    partial void InsertSinavlar(Sinavlar instance);
    partial void UpdateSinavlar(Sinavlar instance);
    partial void DeleteSinavlar(Sinavlar instance);
    #endregion
		
		public VeriTabaniDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["doganvar_veritabaniConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VeriTabaniDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VeriTabaniDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VeriTabaniDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VeriTabaniDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Asistanlar> Asistanlar
		{
			get
			{
				return this.GetTable<Asistanlar>();
			}
		}
		
		public System.Data.Linq.Table<Admin> Admin
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<Bolumler> Bolumler
		{
			get
			{
				return this.GetTable<Bolumler>();
			}
		}
		
		public System.Data.Linq.Table<Dersler> Dersler
		{
			get
			{
				return this.GetTable<Dersler>();
			}
		}
		
		public System.Data.Linq.Table<Derslikler> Derslikler
		{
			get
			{
				return this.GetTable<Derslikler>();
			}
		}
		
		public System.Data.Linq.Table<Izinler> Izinler
		{
			get
			{
				return this.GetTable<Izinler>();
			}
		}
		
		public System.Data.Linq.Table<Sekreterler> Sekreterler
		{
			get
			{
				return this.GetTable<Sekreterler>();
			}
		}
		
		public System.Data.Linq.Table<Sinavlar> Sinavlar
		{
			get
			{
				return this.GetTable<Sinavlar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Asistanlar")]
	public partial class Asistanlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _BolumId;
		
		private string _Adi;
		
		private string _Soyadi;
		
		private System.Nullable<bool> _Cinsiyeti;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBolumIdChanging(System.Nullable<int> value);
    partial void OnBolumIdChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    partial void OnSoyadiChanging(string value);
    partial void OnSoyadiChanged();
    partial void OnCinsiyetiChanging(System.Nullable<bool> value);
    partial void OnCinsiyetiChanged();
    #endregion
		
		public Asistanlar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumId", DbType="Int")]
		public System.Nullable<int> BolumId
		{
			get
			{
				return this._BolumId;
			}
			set
			{
				if ((this._BolumId != value))
				{
					this.OnBolumIdChanging(value);
					this.SendPropertyChanging();
					this._BolumId = value;
					this.SendPropertyChanged("BolumId");
					this.OnBolumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(150)")]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyadi", DbType="NVarChar(150)")]
		public string Soyadi
		{
			get
			{
				return this._Soyadi;
			}
			set
			{
				if ((this._Soyadi != value))
				{
					this.OnSoyadiChanging(value);
					this.SendPropertyChanging();
					this._Soyadi = value;
					this.SendPropertyChanged("Soyadi");
					this.OnSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyeti", DbType="Bit")]
		public System.Nullable<bool> Cinsiyeti
		{
			get
			{
				return this._Cinsiyeti;
			}
			set
			{
				if ((this._Cinsiyeti != value))
				{
					this.OnCinsiyetiChanging(value);
					this.SendPropertyChanging();
					this._Cinsiyeti = value;
					this.SendPropertyChanged("Cinsiyeti");
					this.OnCinsiyetiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Adi;
		
		private string _Soyad;
		
		private string _KullaniciAdi;
		
		private string _Sifre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnKullaniciAdiChanging(string value);
    partial void OnKullaniciAdiChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(150)")]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(150)")]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciAdi", DbType="NVarChar(50)")]
		public string KullaniciAdi
		{
			get
			{
				return this._KullaniciAdi;
			}
			set
			{
				if ((this._KullaniciAdi != value))
				{
					this.OnKullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._KullaniciAdi = value;
					this.SendPropertyChanged("KullaniciAdi");
					this.OnKullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(50)")]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bolumler")]
	public partial class Bolumler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _BolumKod;
		
		private string _BolumAdi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBolumKodChanging(string value);
    partial void OnBolumKodChanged();
    partial void OnBolumAdiChanging(string value);
    partial void OnBolumAdiChanged();
    #endregion
		
		public Bolumler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumKod", DbType="NVarChar(50)")]
		public string BolumKod
		{
			get
			{
				return this._BolumKod;
			}
			set
			{
				if ((this._BolumKod != value))
				{
					this.OnBolumKodChanging(value);
					this.SendPropertyChanging();
					this._BolumKod = value;
					this.SendPropertyChanged("BolumKod");
					this.OnBolumKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumAdi", DbType="NVarChar(500)")]
		public string BolumAdi
		{
			get
			{
				return this._BolumAdi;
			}
			set
			{
				if ((this._BolumAdi != value))
				{
					this.OnBolumAdiChanging(value);
					this.SendPropertyChanging();
					this._BolumAdi = value;
					this.SendPropertyChanged("BolumAdi");
					this.OnBolumAdiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Dersler")]
	public partial class Dersler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _BolumId;
		
		private string _DersKodu;
		
		private string _DersAdi;
		
		private System.Nullable<int> _DersiAlanOgrenciSayisi;
		
		private System.Nullable<bool> _EngelliDurumu;
		
		private string _DersinHocasi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBolumIdChanging(System.Nullable<int> value);
    partial void OnBolumIdChanged();
    partial void OnDersKoduChanging(string value);
    partial void OnDersKoduChanged();
    partial void OnDersAdiChanging(string value);
    partial void OnDersAdiChanged();
    partial void OnDersiAlanOgrenciSayisiChanging(System.Nullable<int> value);
    partial void OnDersiAlanOgrenciSayisiChanged();
    partial void OnEngelliDurumuChanging(System.Nullable<bool> value);
    partial void OnEngelliDurumuChanged();
    partial void OnDersinHocasiChanging(string value);
    partial void OnDersinHocasiChanged();
    #endregion
		
		public Dersler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumId", DbType="Int")]
		public System.Nullable<int> BolumId
		{
			get
			{
				return this._BolumId;
			}
			set
			{
				if ((this._BolumId != value))
				{
					this.OnBolumIdChanging(value);
					this.SendPropertyChanging();
					this._BolumId = value;
					this.SendPropertyChanged("BolumId");
					this.OnBolumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DersKodu", DbType="NVarChar(50)")]
		public string DersKodu
		{
			get
			{
				return this._DersKodu;
			}
			set
			{
				if ((this._DersKodu != value))
				{
					this.OnDersKoduChanging(value);
					this.SendPropertyChanging();
					this._DersKodu = value;
					this.SendPropertyChanged("DersKodu");
					this.OnDersKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DersAdi", DbType="NVarChar(150)")]
		public string DersAdi
		{
			get
			{
				return this._DersAdi;
			}
			set
			{
				if ((this._DersAdi != value))
				{
					this.OnDersAdiChanging(value);
					this.SendPropertyChanging();
					this._DersAdi = value;
					this.SendPropertyChanged("DersAdi");
					this.OnDersAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DersiAlanOgrenciSayisi", DbType="Int")]
		public System.Nullable<int> DersiAlanOgrenciSayisi
		{
			get
			{
				return this._DersiAlanOgrenciSayisi;
			}
			set
			{
				if ((this._DersiAlanOgrenciSayisi != value))
				{
					this.OnDersiAlanOgrenciSayisiChanging(value);
					this.SendPropertyChanging();
					this._DersiAlanOgrenciSayisi = value;
					this.SendPropertyChanged("DersiAlanOgrenciSayisi");
					this.OnDersiAlanOgrenciSayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EngelliDurumu", DbType="Bit")]
		public System.Nullable<bool> EngelliDurumu
		{
			get
			{
				return this._EngelliDurumu;
			}
			set
			{
				if ((this._EngelliDurumu != value))
				{
					this.OnEngelliDurumuChanging(value);
					this.SendPropertyChanging();
					this._EngelliDurumu = value;
					this.SendPropertyChanged("EngelliDurumu");
					this.OnEngelliDurumuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DersinHocasi", DbType="NVarChar(250)")]
		public string DersinHocasi
		{
			get
			{
				return this._DersinHocasi;
			}
			set
			{
				if ((this._DersinHocasi != value))
				{
					this.OnDersinHocasiChanging(value);
					this.SendPropertyChanging();
					this._DersinHocasi = value;
					this.SendPropertyChanged("DersinHocasi");
					this.OnDersinHocasiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Derslikler")]
	public partial class Derslikler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _BolumId;
		
		private string _DerslikKod;
		
		private string _DerslikAdi;
		
		private System.Nullable<int> _DerslikKapasitesi;
		
		private System.Nullable<byte> _DerslikKat;
		
		private string _Aciklama;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBolumIdChanging(System.Nullable<int> value);
    partial void OnBolumIdChanged();
    partial void OnDerslikKodChanging(string value);
    partial void OnDerslikKodChanged();
    partial void OnDerslikAdiChanging(string value);
    partial void OnDerslikAdiChanged();
    partial void OnDerslikKapasitesiChanging(System.Nullable<int> value);
    partial void OnDerslikKapasitesiChanged();
    partial void OnDerslikKatChanging(System.Nullable<byte> value);
    partial void OnDerslikKatChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    #endregion
		
		public Derslikler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumId", DbType="Int")]
		public System.Nullable<int> BolumId
		{
			get
			{
				return this._BolumId;
			}
			set
			{
				if ((this._BolumId != value))
				{
					this.OnBolumIdChanging(value);
					this.SendPropertyChanging();
					this._BolumId = value;
					this.SendPropertyChanged("BolumId");
					this.OnBolumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DerslikKod", DbType="NVarChar(50)")]
		public string DerslikKod
		{
			get
			{
				return this._DerslikKod;
			}
			set
			{
				if ((this._DerslikKod != value))
				{
					this.OnDerslikKodChanging(value);
					this.SendPropertyChanging();
					this._DerslikKod = value;
					this.SendPropertyChanged("DerslikKod");
					this.OnDerslikKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DerslikAdi", DbType="NVarChar(150)")]
		public string DerslikAdi
		{
			get
			{
				return this._DerslikAdi;
			}
			set
			{
				if ((this._DerslikAdi != value))
				{
					this.OnDerslikAdiChanging(value);
					this.SendPropertyChanging();
					this._DerslikAdi = value;
					this.SendPropertyChanged("DerslikAdi");
					this.OnDerslikAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DerslikKapasitesi", DbType="Int")]
		public System.Nullable<int> DerslikKapasitesi
		{
			get
			{
				return this._DerslikKapasitesi;
			}
			set
			{
				if ((this._DerslikKapasitesi != value))
				{
					this.OnDerslikKapasitesiChanging(value);
					this.SendPropertyChanging();
					this._DerslikKapasitesi = value;
					this.SendPropertyChanged("DerslikKapasitesi");
					this.OnDerslikKapasitesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DerslikKat", DbType="TinyInt")]
		public System.Nullable<byte> DerslikKat
		{
			get
			{
				return this._DerslikKat;
			}
			set
			{
				if ((this._DerslikKat != value))
				{
					this.OnDerslikKatChanging(value);
					this.SendPropertyChanging();
					this._DerslikKat = value;
					this.SendPropertyChanged("DerslikKat");
					this.OnDerslikKatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(MAX)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Izinler")]
	public partial class Izinler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _AsistanId;
		
		private string _IzinAdi;
		
		private string _IzinAciklama;
		
		private System.Nullable<System.TimeSpan> _IzinBasSaati;
		
		private System.Nullable<System.TimeSpan> _IzinBitisSaati;
		
		private System.Nullable<System.DateTime> _IzınBasTarihi;
		
		private System.Nullable<System.DateTime> _IzinBitisTarihi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAsistanIdChanging(System.Nullable<int> value);
    partial void OnAsistanIdChanged();
    partial void OnIzinAdiChanging(string value);
    partial void OnIzinAdiChanged();
    partial void OnIzinAciklamaChanging(string value);
    partial void OnIzinAciklamaChanged();
    partial void OnIzinBasSaatiChanging(System.Nullable<System.TimeSpan> value);
    partial void OnIzinBasSaatiChanged();
    partial void OnIzinBitisSaatiChanging(System.Nullable<System.TimeSpan> value);
    partial void OnIzinBitisSaatiChanged();
    partial void OnIzınBasTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnIzınBasTarihiChanged();
    partial void OnIzinBitisTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnIzinBitisTarihiChanged();
    #endregion
		
		public Izinler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsistanId", DbType="Int")]
		public System.Nullable<int> AsistanId
		{
			get
			{
				return this._AsistanId;
			}
			set
			{
				if ((this._AsistanId != value))
				{
					this.OnAsistanIdChanging(value);
					this.SendPropertyChanging();
					this._AsistanId = value;
					this.SendPropertyChanged("AsistanId");
					this.OnAsistanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinAdi", DbType="NVarChar(150)")]
		public string IzinAdi
		{
			get
			{
				return this._IzinAdi;
			}
			set
			{
				if ((this._IzinAdi != value))
				{
					this.OnIzinAdiChanging(value);
					this.SendPropertyChanging();
					this._IzinAdi = value;
					this.SendPropertyChanged("IzinAdi");
					this.OnIzinAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinAciklama", DbType="NVarChar(MAX)")]
		public string IzinAciklama
		{
			get
			{
				return this._IzinAciklama;
			}
			set
			{
				if ((this._IzinAciklama != value))
				{
					this.OnIzinAciklamaChanging(value);
					this.SendPropertyChanging();
					this._IzinAciklama = value;
					this.SendPropertyChanged("IzinAciklama");
					this.OnIzinAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinBasSaati", DbType="Time")]
		public System.Nullable<System.TimeSpan> IzinBasSaati
		{
			get
			{
				return this._IzinBasSaati;
			}
			set
			{
				if ((this._IzinBasSaati != value))
				{
					this.OnIzinBasSaatiChanging(value);
					this.SendPropertyChanging();
					this._IzinBasSaati = value;
					this.SendPropertyChanged("IzinBasSaati");
					this.OnIzinBasSaatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinBitisSaati", DbType="Time")]
		public System.Nullable<System.TimeSpan> IzinBitisSaati
		{
			get
			{
				return this._IzinBitisSaati;
			}
			set
			{
				if ((this._IzinBitisSaati != value))
				{
					this.OnIzinBitisSaatiChanging(value);
					this.SendPropertyChanging();
					this._IzinBitisSaati = value;
					this.SendPropertyChanged("IzinBitisSaati");
					this.OnIzinBitisSaatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzınBasTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> IzınBasTarihi
		{
			get
			{
				return this._IzınBasTarihi;
			}
			set
			{
				if ((this._IzınBasTarihi != value))
				{
					this.OnIzınBasTarihiChanging(value);
					this.SendPropertyChanging();
					this._IzınBasTarihi = value;
					this.SendPropertyChanged("IzınBasTarihi");
					this.OnIzınBasTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IzinBitisTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> IzinBitisTarihi
		{
			get
			{
				return this._IzinBitisTarihi;
			}
			set
			{
				if ((this._IzinBitisTarihi != value))
				{
					this.OnIzinBitisTarihiChanging(value);
					this.SendPropertyChanging();
					this._IzinBitisTarihi = value;
					this.SendPropertyChanged("IzinBitisTarihi");
					this.OnIzinBitisTarihiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sekreterler")]
	public partial class Sekreterler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _BolumId;
		
		private string _Adi;
		
		private string _Soyadi;
		
		private string _KullaniciAdi;
		
		private string _Sifre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBolumIdChanging(System.Nullable<int> value);
    partial void OnBolumIdChanged();
    partial void OnAdiChanging(string value);
    partial void OnAdiChanged();
    partial void OnSoyadiChanging(string value);
    partial void OnSoyadiChanged();
    partial void OnKullaniciAdiChanging(string value);
    partial void OnKullaniciAdiChanged();
    partial void OnSifreChanging(string value);
    partial void OnSifreChanged();
    #endregion
		
		public Sekreterler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumId", DbType="Int")]
		public System.Nullable<int> BolumId
		{
			get
			{
				return this._BolumId;
			}
			set
			{
				if ((this._BolumId != value))
				{
					this.OnBolumIdChanging(value);
					this.SendPropertyChanging();
					this._BolumId = value;
					this.SendPropertyChanged("BolumId");
					this.OnBolumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adi", DbType="NVarChar(150)")]
		public string Adi
		{
			get
			{
				return this._Adi;
			}
			set
			{
				if ((this._Adi != value))
				{
					this.OnAdiChanging(value);
					this.SendPropertyChanging();
					this._Adi = value;
					this.SendPropertyChanged("Adi");
					this.OnAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyadi", DbType="NVarChar(150)")]
		public string Soyadi
		{
			get
			{
				return this._Soyadi;
			}
			set
			{
				if ((this._Soyadi != value))
				{
					this.OnSoyadiChanging(value);
					this.SendPropertyChanging();
					this._Soyadi = value;
					this.SendPropertyChanged("Soyadi");
					this.OnSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciAdi", DbType="NVarChar(150)")]
		public string KullaniciAdi
		{
			get
			{
				return this._KullaniciAdi;
			}
			set
			{
				if ((this._KullaniciAdi != value))
				{
					this.OnKullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._KullaniciAdi = value;
					this.SendPropertyChanged("KullaniciAdi");
					this.OnKullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sifre", DbType="NVarChar(150)")]
		public string Sifre
		{
			get
			{
				return this._Sifre;
			}
			set
			{
				if ((this._Sifre != value))
				{
					this.OnSifreChanging(value);
					this.SendPropertyChanging();
					this._Sifre = value;
					this.SendPropertyChanged("Sifre");
					this.OnSifreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sinavlar")]
	public partial class Sinavlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _BolumId;
		
		private System.Nullable<int> _DersId;
		
		private System.Nullable<int> _DerslikId;
		
		private string _AsistanId;
		
		private System.Nullable<System.DateTime> _Tarih;
		
		private System.Nullable<System.TimeSpan> _BaslangicSaati;
		
		private System.Nullable<System.TimeSpan> _BitisSaati;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBolumIdChanging(System.Nullable<int> value);
    partial void OnBolumIdChanged();
    partial void OnDersIdChanging(System.Nullable<int> value);
    partial void OnDersIdChanged();
    partial void OnDerslikIdChanging(System.Nullable<int> value);
    partial void OnDerslikIdChanged();
    partial void OnAsistanIdChanging(string value);
    partial void OnAsistanIdChanged();
    partial void OnTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnTarihChanged();
    partial void OnBaslangicSaatiChanging(System.Nullable<System.TimeSpan> value);
    partial void OnBaslangicSaatiChanged();
    partial void OnBitisSaatiChanging(System.Nullable<System.TimeSpan> value);
    partial void OnBitisSaatiChanged();
    #endregion
		
		public Sinavlar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BolumId", DbType="Int")]
		public System.Nullable<int> BolumId
		{
			get
			{
				return this._BolumId;
			}
			set
			{
				if ((this._BolumId != value))
				{
					this.OnBolumIdChanging(value);
					this.SendPropertyChanging();
					this._BolumId = value;
					this.SendPropertyChanged("BolumId");
					this.OnBolumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DersId", DbType="Int")]
		public System.Nullable<int> DersId
		{
			get
			{
				return this._DersId;
			}
			set
			{
				if ((this._DersId != value))
				{
					this.OnDersIdChanging(value);
					this.SendPropertyChanging();
					this._DersId = value;
					this.SendPropertyChanged("DersId");
					this.OnDersIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DerslikId", DbType="Int")]
		public System.Nullable<int> DerslikId
		{
			get
			{
				return this._DerslikId;
			}
			set
			{
				if ((this._DerslikId != value))
				{
					this.OnDerslikIdChanging(value);
					this.SendPropertyChanging();
					this._DerslikId = value;
					this.SendPropertyChanged("DerslikId");
					this.OnDerslikIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsistanId", DbType="NVarChar(50)")]
		public string AsistanId
		{
			get
			{
				return this._AsistanId;
			}
			set
			{
				if ((this._AsistanId != value))
				{
					this.OnAsistanIdChanging(value);
					this.SendPropertyChanging();
					this._AsistanId = value;
					this.SendPropertyChanged("AsistanId");
					this.OnAsistanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="Date")]
		public System.Nullable<System.DateTime> Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaslangicSaati", DbType="Time")]
		public System.Nullable<System.TimeSpan> BaslangicSaati
		{
			get
			{
				return this._BaslangicSaati;
			}
			set
			{
				if ((this._BaslangicSaati != value))
				{
					this.OnBaslangicSaatiChanging(value);
					this.SendPropertyChanging();
					this._BaslangicSaati = value;
					this.SendPropertyChanged("BaslangicSaati");
					this.OnBaslangicSaatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BitisSaati", DbType="Time")]
		public System.Nullable<System.TimeSpan> BitisSaati
		{
			get
			{
				return this._BitisSaati;
			}
			set
			{
				if ((this._BitisSaati != value))
				{
					this.OnBitisSaatiChanging(value);
					this.SendPropertyChanging();
					this._BitisSaati = value;
					this.SendPropertyChanged("BitisSaati");
					this.OnBitisSaatiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
